[package]
name = "maid-felix"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
dotenv = "0.15.0"
scraper = "0.13.0"
reqwest = { version = "0.11.11", features = ["blocking", "cookies"] }
